import {
  Award,
  BarChart3,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Compass,
  GraduationCap,
  Globe,
  Handshake,
  Heart,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Rocket,
  Shield,
  Sparkles,
  Star,
  Target,
  Trophy,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { ProgramHeaderIconKey } from "./schema";

/** Maps a stored icon key to its `lucide-react` component. */
export const PROGRAM_HEADER_ICONS: Record<ProgramHeaderIconKey, LucideIcon> = {
  layers: Layers,
  rocket: Rocket,
  graduation: GraduationCap,
  users: Users,
  handshake: Handshake,
  building: Building2,
  landmark: Landmark,
  globe: Globe,
  award: Award,
  trophy: Trophy,
  target: Target,
  compass: Compass,
  sparkles: Sparkles,
  star: Star,
  lightbulb: Lightbulb,
  book: BookOpen,
  briefcase: Briefcase,
  calendar: Calendar,
  chart: BarChart3,
  heart: Heart,
  leaf: Leaf,
  shield: Shield,
};
