import {
  Award,
  Banknote,
  BookOpen,
  Briefcase,
  Building2,
  Compass,
  Flag,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  Landmark,
  Leaf,
  Lightbulb,
  Network,
  Shield,
  Sparkles,
  Star,
  Target,
  Trophy,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { PartnerIconKey } from "./schema";

/** Maps a stored icon key to its `lucide-react` component. */
export const PARTNER_ICONS: Record<PartnerIconKey, LucideIcon> = {
  building: Building2,
  landmark: Landmark,
  handshake: Handshake,
  globe: Globe,
  users: Users,
  award: Award,
  briefcase: Briefcase,
  flag: Flag,
  shield: Shield,
  star: Star,
  sparkles: Sparkles,
  target: Target,
  book: BookOpen,
  graduation: GraduationCap,
  leaf: Leaf,
  heart: Heart,
  banknote: Banknote,
  gift: Gift,
  network: Network,
  trophy: Trophy,
  lightbulb: Lightbulb,
  compass: Compass,
};
